/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.sql.ResultSet;
import com.mysql.jdbc.Statement;
import javax.swing.JOptionPane;
import koneksi.connect;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Cryan
 */
public class gaji extends javax.swing.JFrame {
String id_gajii="";
    /**
     * Creates new form gaji
     */
    public gaji() {
        initComponents();
        getDataKaryawan();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_idGaji = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_gajiKotor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_jamLembur = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_pajak = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_gajiBersih = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_bulan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_tahun = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_jabatan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_gajiPokok = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_upahLembur = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_tunjanganAnak = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        txt_tunjanganIstri = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_gajiLembur = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Penggajian");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID_GAJI");

        txt_idGaji.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ID_KARYAWAN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Gaji Kotor");

        txt_gajiKotor.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Jam Lembur");

        txt_jamLembur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_jamLemburKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Pajak");

        txt_pajak.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Gaji Bersih");

        txt_gajiBersih.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Bulan");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tahun");

        txt_tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tahunActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Jabatan");

        txt_jabatan.setEnabled(false);
        txt_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jabatanActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Gaji Pokok");

        txt_gajiPokok.setEnabled(false);
        txt_gajiPokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gajiPokokActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Upah Lembur");

        txt_upahLembur.setEnabled(false);
        txt_upahLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_upahLemburActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Tunjangan Anak");

        txt_tunjanganAnak.setEnabled(false);
        txt_tunjanganAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tunjanganAnakActionPerformed(evt);
            }
        });

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Save-icon.png"))); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_bersih.setText("Bersih");
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/hapus.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);

        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Tunjangan Istri");

        txt_tunjanganIstri.setEnabled(false);
        txt_tunjanganIstri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tunjanganIstriActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Gaji Lembur");

        txt_gajiLembur.setEnabled(false);
        txt_gajiLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gajiLemburActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Home-icon.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Man-icon.png"))); // NOI18N
        jButton2.setText("Karyawan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Relationship-icon.png"))); // NOI18N
        jButton3.setText("Jabatan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Cash-icon.png"))); // NOI18N
        jButton4.setText("Gaji");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel21)
                                                        .addComponent(jLabel22)
                                                        .addComponent(jLabel17)
                                                        .addComponent(jLabel16)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel19)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel4))
                                                    .addGap(30, 30, 30)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txt_jamLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_gajiLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_pajak, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_gajiBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_gajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_tunjanganIstri, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_tunjanganAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_upahLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_gajiKotor, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt_idGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(170, 170, 170))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(762, 762, 762))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 754, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel2)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_cari)
                                            .addComponent(btn_cari, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                            .addComponent(txt_idGaji, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_gajiKotor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_jamLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_bulan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_gajiLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txt_pajak, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_gajiBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txt_gajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txt_upahLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txt_tunjanganAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_tunjanganIstri, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void datatable(){
        DefaultTableModel tbl= new DefaultTableModel();
        tbl.addColumn("idGaji");
        tbl.addColumn("IdKaryawan");
        tbl.addColumn("Nama Karyawan");
        tbl.addColumn("Gaji Kotor");
        tbl.addColumn("Jumlah Lembur");
        tbl.addColumn("Pajak");
        tbl.addColumn("Total Tunjangan");
        tbl.addColumn("Gaji Bersih");
        tbl.addColumn("Bulan");
        tbl.addColumn("Tahun");
        dataTable.setModel(tbl);
        try{
            Statement statement = (Statement) connect.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from tbl_penggajian as p INNER JOIN tbl_karyawan as k ON p.id_karyawan = k.id_karyawan");
            while(res.next())
            {
                tbl.addRow(new Object[]{
                res.getString("id_penggajian"),
                res.getString("id_karyawan"),
                res.getString("nama_karyawan"),
                res.getString("gaji_kotor"),
                res.getString("jumlah_lembur"),
                res.getString("pajak"),
                res.getString("total_tunjangan"),
                res.getString("gaji_bersih"),
                res.getString("bulan"),
                res.getString("tahun"),
                });
                dataTable.setModel(tbl);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    private void getDataKaryawan(){
        try{
            jComboBox1.removeAllItems();
            Statement statement = (Statement) connect.getConnection().createStatement();
            ResultSet result = statement.executeQuery("SELECT * FROM tbl_karyawan");
            while(result.next()){
                String id_karyawan = result.getString("id_karyawan").toString();
                String nama_karyawan = result.getString("nama_karyawan").toString();
                jComboBox1.addItem(id_karyawan+" - "+nama_karyawan);
            }
        }catch(Exception err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    
    private void txt_tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tahunActionPerformed

    private void txt_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jabatanActionPerformed

    private void txt_gajiPokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gajiPokokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gajiPokokActionPerformed

    private void txt_upahLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_upahLemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_upahLemburActionPerformed

    private void txt_tunjanganAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tunjanganAnakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tunjanganAnakActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
//        try{
//        String tmp = (String) jComboBox1.getSelectedItem();
//        Statement statement = (Statement) connect.getConnection().createStatement();
//        ResultSet res = statement.executeQuery("SELECT * FROM tbl_karyawan WHERE nama_karyawan='"+ tmp +"'");
//        if(res.next()){
//            String add = res.getString("nama_karyawan");
//            txt_jamLembur.setText(add);
//        }
//        } catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void hitungGaji(){
        Integer gaji_pokok = Integer.parseInt(txt_gajiPokok.getText());
        Integer total_gaji_lembur = Integer.parseInt(txt_gajiLembur.getText());
        Integer tunjangan_istri = Integer.parseInt(txt_tunjanganIstri.getText());
        Integer tunjangan_anak = Integer.parseInt(txt_tunjanganAnak.getText());
        Integer gaji_kotor = gaji_pokok+tunjangan_istri+tunjangan_anak;
        Integer pajak_karyawan = gaji_kotor*10/100;
        Integer gaji_bersih = (gaji_kotor+total_gaji_lembur)-pajak_karyawan;
        
        txt_gajiKotor.setText(gaji_kotor.toString());
        txt_pajak.setText(pajak_karyawan.toString());
        txt_gajiBersih.setText(gaji_bersih.toString());
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String value = jComboBox1.getSelectedItem().toString();
        String[] arrValue = value.split(" - ");
        String id_karyawan = arrValue[0];
        
        try{
            Statement statement = (Statement) connect.getConnection().createStatement();
            ResultSet result = statement.executeQuery("SELECT * FROM tbl_karyawan WHERE id_karyawan='"+id_karyawan+"' ");
            if(result.next()){
                String kode_jabatan = result.getString("kode_jabatan");
                String status_karyawan = result.getString("status");
                String jml_anak = result.getString("jml_anak");
                try{
                    ResultSet result2 = statement.executeQuery("SELECT * FROM tbl_jabatan WHERE kode_jabatan='"+kode_jabatan+"' ");
                    if(result2.next()){
                        String nama_jabatan = result2.getString("nama_jabatan");
                        String gaji_pokok = result2.getString("jml_gaji_pokok");
                        String upah_lembur = result2.getString("upah_lembur");
                        Integer tunjangan_istri;
                        Integer tunjangan_anak;
                        
                        if("BelumMenikah".equals(status_karyawan)){
                            tunjangan_istri = 0;
                            tunjangan_anak = 0;
                        }else{
                            tunjangan_istri = Integer.parseInt(gaji_pokok)*20/100;
                            if(Integer.parseInt(jml_anak) <= 2){
                                tunjangan_anak = (Integer.parseInt(gaji_pokok)*Integer.parseInt(jml_anak))*15/100;
                            }else if(Integer.parseInt(jml_anak) >= 2){
                                tunjangan_anak = (Integer.parseInt(gaji_pokok)*2)*15/100;
                            } else{
                                tunjangan_anak = 0;
                            }
                        }
                        
                        txt_gajiPokok.setText(gaji_pokok);
                        txt_upahLembur.setText(upah_lembur);
                        txt_tunjanganIstri.setText(tunjangan_istri.toString());
                        txt_tunjanganAnak.setText(tunjangan_anak.toString());
                        txt_jabatan.setText(nama_jabatan.toString());
                        
                    }
                }catch(Exception err){
                    JOptionPane.showMessageDialog(null, err.getMessage());
                }
            }
        }catch(Exception err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txt_tunjanganIstriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tunjanganIstriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tunjanganIstriActionPerformed

    private void txt_gajiLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gajiLemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gajiLemburActionPerformed

    private void txt_jamLemburKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jamLemburKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            Integer upah_lembur = Integer.parseInt(txt_upahLembur.getText());
            Integer jam_lembur = Integer.parseInt(txt_jamLembur.getText());
            Integer total_gaji_lembur = upah_lembur*jam_lembur;
        
            txt_gajiLembur.setText(total_gaji_lembur.toString());
            hitungGaji();
        }
    }//GEN-LAST:event_txt_jamLemburKeyPressed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String value = jComboBox1.getSelectedItem().toString();
        String[] arrValue = value.split(" - ");
        String id_karyawan = arrValue[0];
        String gaji_kotor = txt_gajiKotor.getText();
        String jumlah_lembur = txt_gajiLembur.getText();
        String pajak = txt_pajak.getText();
        String tunjangan_istri = txt_tunjanganIstri.getText();
        String tunjangan_anak = txt_tunjanganAnak.getText();
        Integer total_tunjangan = Integer.parseInt(tunjangan_istri)+Integer.parseInt(tunjangan_anak);
        String gaji_bersih = txt_gajiBersih.getText();
        String bulan = txt_bulan.getText();
        String tahun = txt_tahun.getText();
        try {
            Statement statement = (Statement) connect.getConnection().createStatement();
            statement.executeUpdate("insert into tbl_penggajian (id_karyawan, gaji_kotor, jumlah_lembur, pajak, total_tunjangan, gaji_bersih, bulan, tahun)VALUES('" + id_karyawan + "','" + gaji_kotor + "','" + jumlah_lembur + "','" + pajak + "','" + total_tunjangan + "','" + gaji_bersih + "','" + bulan + "','" + tahun + "');");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan" + t.getMessage());
        }
        datatable();
    }//GEN-LAST:event_btn_simpanActionPerformed

    
    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        // TODO add your handling code here:
       btn_hapus.setEnabled(true);
    }//GEN-LAST:event_dataTableMouseClicked

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        // TODO add your handling code here:
        txt_idGaji.setText("");
        txt_jamLembur.setText("");
        txt_bulan.setText("");
        txt_tahun.setText("");
        txt_gajiLembur.setText("");
    }//GEN-LAST:event_btn_bersihActionPerformed

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        dataTable.getSelectedRow();
        Object id_gaji = model.getValueAt(dataTable.getSelectedRow(), 0);
        try{
            Statement stmt = (Statement) connect.getConnection().createStatement();
            stmt.executeUpdate("DELETE FROM tbl_penggajian WHERE id_penggajian='"+id_gaji+"' ");
            stmt.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
        }catch(Exception err){
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
        datatable();
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new karyawan().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new jabatan().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        try {
            Statement statement = (Statement) connect.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from  tbl_penggajian as p INNER JOIN tbl_karyawan as k ON p.id_karyawan = k.id_karyawan where "+" k.nama_karyawan like '%"+txt_cari.getText()+"%'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("idGaji");
            tbl.addColumn("IdKaryawan");
            tbl.addColumn("Nama Karyawan");
            tbl.addColumn("Gaji Kotor");
            tbl.addColumn("Jumlah Lembur");
            tbl.addColumn("Pajak");
            tbl.addColumn("Total Tunjangan");
            tbl.addColumn("Gaji Bersih");
            tbl.addColumn("Bulan");
            tbl.addColumn("Tahun");
            dataTable.setModel(tbl);
            while (res.next()) {
                tbl.addRow(new Object[]{
                res.getString("id_penggajian"),
                res.getString("id_karyawan"),
                res.getString("nama_karyawan"),
                res.getString("gaji_kotor"),
                res.getString("jumlah_lembur"),
                res.getString("pajak"),
                res.getString("total_tunjangan"),
                res.getString("gaji_bersih"),
                res.getString("bulan"),
                res.getString("tahun"),
                });
                dataTable.setModel(tbl);
            }
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data berhasil di cari" + t.getMessage());
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new gaji().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_bulan;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_gajiBersih;
    private javax.swing.JTextField txt_gajiKotor;
    private javax.swing.JTextField txt_gajiLembur;
    private javax.swing.JTextField txt_gajiPokok;
    private javax.swing.JTextField txt_idGaji;
    private javax.swing.JTextField txt_jabatan;
    private javax.swing.JTextField txt_jamLembur;
    private javax.swing.JTextField txt_pajak;
    private javax.swing.JTextField txt_tahun;
    private javax.swing.JTextField txt_tunjanganAnak;
    private javax.swing.JTextField txt_tunjanganIstri;
    private javax.swing.JTextField txt_upahLembur;
    // End of variables declaration//GEN-END:variables
}
