/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.sql.ResultSet;
import com.mysql.jdbc.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import koneksi.connect;
import java.text.SimpleDateFormat;
import java.sql.Date;
/**
 *
 * @author Cryan
 */
public class karyawan extends javax.swing.JFrame {
    String id_karyawann = "";
    /**
     * Creates new form karyawan
     */
    public karyawan() {
        initComponents();
//        combo();
        datatable();
        tampilJabatan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void datatable(){
        DefaultTableModel tbl= new DefaultTableModel();
        tbl.addColumn("ID");
        tbl.addColumn("Nama");
        tbl.addColumn("Alamat");
        tbl.addColumn("NOHP");
        tbl.addColumn("Tempat Lahir");
        tbl.addColumn("Tanggal Lahir");
        tbl.addColumn("Jenis Kelamin");
        tbl.addColumn("Kode Jabatan");
        tbl.addColumn("Jabatan");
        tbl.addColumn("Status");
        tbl.addColumn("Jumlah Anak");
        dataTable.setModel(tbl);
        try{
            Statement statement = (Statement) connect.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from tbl_karyawan as k INNER JOIN tbl_jabatan as j ON k.kode_jabatan = j.kode_jabatan");
            while(res.next())
            {
                tbl.addRow(new Object[]{
                res.getString("id_karyawan"),
                res.getString("nama_karyawan"),
                res.getString("alamat"),
                res.getString("no_hp"),
                res.getString("tempat_lahir"),
                res.getString("tanggal_lahir"),
                res.getString("jenis_kelamin"),
                res.getString("kode_jabatan"),
                res.getString("nama_jabatan"),
                res.getString("status"),
                res.getString("jml_anak"),
                });
                dataTable.setModel(tbl);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    
    
    private void tampilJabatan(){
        try{
            Statement panggil = (Statement) connect.getConnection().createStatement();
            ResultSet res = panggil.executeQuery("SELECT * FROM tbl_jabatan");
            while(res.next()){
                cmb_kodeJabatan.addItem(res.getString("kode_jabatan"));
            }
            panggil.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"GAGAL", "error", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_namaKaryawan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txt_noHp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_tempatLahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmb_jenisKelamin = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cmb_kodeJabatan = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cmb_status = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_bersih = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        btn_cari = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        txt_jumlahAnak = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("KARYAWAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Karyawan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Alamat");

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        jScrollPane1.setViewportView(txt_alamat);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nomor HP");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tempat Lahir");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Lahir");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jenis Kelamin");

        cmb_jenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-Laki", "Perempuan" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kode Jabatan");

        cmb_kodeJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_kodeJabatanActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Status");

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SudahMenikah", "BelumMenikah" }));
        cmb_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_statusMouseClicked(evt);
            }
        });
        cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statusActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Jumlah Anak");

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dataTable);

        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Save-icon.png"))); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_bersih.setText("Bersih");
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/edit.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/hapus.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("ID_KARYAWAN");

        txt_id.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Home-icon.png"))); // NOI18N
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Man-icon.png"))); // NOI18N
        jButton2.setText("Karyawan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Relationship-icon.png"))); // NOI18N
        jButton3.setText("Jabatan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/Cash-icon.png"))); // NOI18N
        jButton4.setText("Gaji");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmb_status, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_kodeJabatan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb_jenisKelamin, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_tempatLahir, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_noHp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_namaKaryawan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_jumlahAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(32, 32, 32)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(btn_bersih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cari)
                                .addGap(334, 334, 334))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_namaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_noHp, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_kodeJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_jumlahAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String nama_karyawan = txt_namaKaryawan.getText();
        String alamat = txt_alamat.getText();
        String no_hp = txt_noHp.getText();
        String tempat_lahir = txt_tempatLahir.getText(); 
        SimpleDateFormat tanggal;
        tanggal = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal_lahir = tanggal.format(date.getDate());
        String jenis_kelamin = (String) cmb_jenisKelamin.getSelectedItem();
        String kode_jabatan = (String) cmb_kodeJabatan.getSelectedItem(); 
        String status = (String) cmb_status.getSelectedItem(); 
        String jml_anak = txt_jumlahAnak.getText();
        try {
            Statement statement = (Statement) connect.getConnection().createStatement();
            statement.executeUpdate("insert into tbl_karyawan (nama_karyawan, alamat, no_hp, tempat_lahir, tanggal_lahir, jenis_kelamin, kode_jabatan, status, jml_anak)VALUES('" + nama_karyawan + "','" + alamat + "','" + no_hp + "','" + tempat_lahir + "','" + tanggal_lahir + "','" + jenis_kelamin + "','" + kode_jabatan + "','" + status + "','" + jml_anak + "');");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan" + t.getMessage());
        }
        datatable();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void cmb_kodeJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kodeJabatanActionPerformed
        // TODO add your handling code here:
//        tampilJabatan();
    }//GEN-LAST:event_cmb_kodeJabatanActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        // TODO add your handling code here:
        txt_id.setText("");
        txt_namaKaryawan.setText("");
        txt_alamat.setText("");
        txt_noHp.setText("");
        txt_tempatLahir.setText("");
        txt_jumlahAnak.setText("");
    }//GEN-LAST:event_btn_bersihActionPerformed

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        dataTable.getSelectedRow();
        Object id=model.getValueAt(dataTable.getSelectedRow(), 0);
        id_karyawann=(String)id;
        txt_id.setText(String.valueOf(id));
        Object nama_karyawan=model.getValueAt(dataTable.getSelectedRow(), 1);
        txt_namaKaryawan.setText(String.valueOf(nama_karyawan));
        Object alamat=model.getValueAt(dataTable.getSelectedRow(), 2);
        txt_alamat.setText(String.valueOf(alamat));
        Object no_hp=model.getValueAt(dataTable.getSelectedRow(), 3);
        txt_noHp.setText(String.valueOf(no_hp));
        Object tempat_lahir=model.getValueAt(dataTable.getSelectedRow(), 4);
        txt_tempatLahir.setText(String.valueOf(tempat_lahir));
        Object tanggal_lahir = model.getValueAt(dataTable.getSelectedRow(), 5);
        date.setDate(Date.valueOf(String.valueOf(tanggal_lahir)));
        Object jenis_kelamin = model.getValueAt(dataTable.getSelectedRow(), 6);
        cmb_jenisKelamin.setSelectedItem(String.valueOf(jenis_kelamin));
        Object kode_jabatan = model.getValueAt(dataTable.getSelectedRow(), 7);
        cmb_kodeJabatan.setSelectedItem(String.valueOf(kode_jabatan));
        Object status = model.getValueAt(dataTable.getSelectedRow(), 9);
        cmb_status.setSelectedItem(String.valueOf(status));
        Object jml_anak=model.getValueAt(dataTable.getSelectedRow(), 10);
        txt_jumlahAnak.setText(String.valueOf(jml_anak));
    }//GEN-LAST:event_dataTableMouseClicked

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
        // TODO add your handling code here:
        if (cmb_status.getSelectedItem() == "SudahMenikah") {
            txt_jumlahAnak.setEnabled(true);
        } else if (cmb_status.getSelectedItem() == "BelumMenikah") {
            txt_jumlahAnak.setEnabled(false);
            txt_jumlahAnak.setText("0");
        }
    }//GEN-LAST:event_cmb_statusActionPerformed

    private void cmb_statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_statusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_statusMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            Statement statement = (Statement) connect.getConnection().createStatement();
            statement.executeUpdate("Delete FROM tbl_karyawan WHERE id_karyawan='" + id_karyawann + "'");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil Dihapus");
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus" + t.getMessage());
        }
        datatable();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        try {
            Statement statement = (Statement) connect.getConnection().createStatement();
            ResultSet res = statement.executeQuery("Select * from tbl_karyawan where "+" nama_karyawan like '%"+txt_cari.getText()+"%'");
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Nama");
            tbl.addColumn("Alamat");
            tbl.addColumn("NOHP");
            tbl.addColumn("Tempat Lahir");
            tbl.addColumn("Tanggal Lahir");
            tbl.addColumn("Jenis Kelamin");
            tbl.addColumn("Kode Jabatan");
            tbl.addColumn("Status");
            tbl.addColumn("Jumlah Anak");
            dataTable.setModel(tbl);
            while (res.next()) {
                tbl.addRow(new Object[]{
                res.getString("nama_karyawan"),
                res.getString("alamat"),
                res.getString("no_hp"),
                res.getString("tempat_lahir"),
                res.getString("tanggal_lahir"),
                res.getString("jenis_kelamin"),
                res.getString("kode_jabatan"),
                res.getString("status"),
                res.getString("jml_anak"),
                });
                dataTable.setModel(tbl);
            }
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data berhasil di cari" + t.getMessage());
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        String id_karyawan = txt_id.getText();
        String nama_karyawan = txt_namaKaryawan.getText();
        String alamat = txt_alamat.getText();
        String no_hp = txt_noHp.getText();
        String tempat_lahir = txt_tempatLahir.getText(); 
        SimpleDateFormat tanggal;
        tanggal = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal_lahir = tanggal.format(date.getDate());
        String jenis_kelamin = (String) cmb_jenisKelamin.getSelectedItem();
        String kode_jabatan = (String) cmb_kodeJabatan.getSelectedItem(); 
        String status = (String) cmb_status.getSelectedItem(); 
        String jml_anak = txt_jumlahAnak.getText();
        try {
            Statement statement = (Statement) connect.getConnection().createStatement();
            statement.executeUpdate("update tbl_karyawan set nama_karyawan='"+ nama_karyawan +"',alamat='" + alamat + "',no_hp='" + no_hp + "', tempat_lahir='" + tempat_lahir + "',tanggal_lahir='" + tanggal_lahir + "',jenis_kelamin='" + jenis_kelamin + "',kode_jabatan='" + kode_jabatan + "',status='" + status + "',jml_anak='" + jml_anak + "' where id_karyawan='"+ id_karyawan +"'");
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan" + t.getMessage());
        }
        datatable();
    }//GEN-LAST:event_btn_editActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new jabatan().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new gaji().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new karyawan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bersih;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox cmb_jenisKelamin;
    private javax.swing.JComboBox cmb_kodeJabatan;
    private javax.swing.JComboBox cmb_status;
    private javax.swing.JTable dataTable;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_jumlahAnak;
    private javax.swing.JTextField txt_namaKaryawan;
    private javax.swing.JTextField txt_noHp;
    private javax.swing.JTextField txt_tempatLahir;
    // End of variables declaration//GEN-END:variables
}
